export const nicknames = {
    '3bac': 'Threepio & Chewie',
    '3bacca': 'Threepio & Chewie',
    '3pac': 'Threepio & Chewie',
    arc: 'ARC Trooper',
    chewpio: 'Threepio & Chewie',
    chewy: 'Chewbacca',
    cls: 'Commander Luke Skywalker',
    daka: 'Old Daka',
    dbast: 'Bastila Shan (Fallen)',
    dr: 'Darth Revan',
    dt: 'Death Trooper',
    dv: 'Darth Vader',
    ep: 'Emperor Palpatine',
    gas: 'General Skywalker',
    gat: 'Grand Admiral Thrawn',
    gg: 'General Grievous',
    gk: 'General Kenobi',
    gsol: 'Geonosian Soldier',
    foo: 'First Order Officer',
    fosf: 'First Order SF TIE Pilot',
    fosftp: 'First Order SF TIE Pilot',
    fost: 'First Order Stormtrooper',
    fotp: 'First Order TIE Pilot',
    hs: 'Han Solo',
    ht: 'Hound\'s Tooth',
    hoda: 'Hermit Yoda',
    jka: 'Jedi Knight Anakin',
    jkl: 'Jedi Knight Luke Skywalker',
    jkr: 'Jedi Knight Revan',
    jtr: 'Rey (Jedi Training)',
    kira: 'Qi\'ra',
    kru: 'Kylo Ren (Unmasked)',
    mal: 'Darth Malak',
    malak: 'Darth Malak',
    mando: 'The Mandalorian',
    mm: 'Mon Mothma',
    mt: 'Mother Talzin',
    nest: 'Enfys Nest',
    ob1: 'Obi-Wan Kenobi (Old Ben)',
    pao: 'Pao',
    pl: 'Princess Leia',
    rex: 'CT-7567 "Rex"',
    rey: 'Rey',
    rhf: 'Resistance Hero Finn',
    rfp: 'Resistance Hero Poe',
    rt: 'Resistance Trooper',
    sa: 'Sith Assassin',
    scav: 'Rey (Scavenger)',
    scavrey: 'Rey (Scavenger)',
    set: 'Sith Empire Trooper',
    slkr: 'Supreme Leader Kylo Ren',
    sm: 'Sith Marauder',
    srp: 'Scarif Rebel Pathfinder',
    st: 'Sith Trooper',
    sthan: 'Stormtrooper Han',
    tf: 'TIE Fighter Pilot',
    tfp: 'TIE Fighter Pilot',
}
